### ISSUE TITLE
ModuleNotFoundError: No module named 'beambending'

### ISSUE THREAD

**Issue by DBG333** [alfredocarella/simplebendingpractice#13]
pip list
beambending  1.1.1  

import os
from beambending import Beam, DistributedLoadV, PointLoadH, PointLoadV, x

I am using pyscripter version 4.3.4.0 x 64
ModuleNotFoundError: No module named 'beambending'
>>> 
*** Remote Interpreter Reinitialized ***
Traceback (most recent call last):
  File "H:\n.py", line 2, in <module>
    from beambending import Beam, DistributedLoadV, PointLoadH, PointLoadV, x
ModuleNotFoundError: No module named 'beambending'
>>> 

Please Help me

**Comment by alfredocarella** [comment]
I am afraid I cannot reproduce your issue. 

Could you confirm whether the package is being installed in the same environment on which the script is being run?
It seems that the interpreter does not have access to the `beambending` module.

If the following line shows beambending installed:
`python -m pip list`

then you can try importing the package with that same interpreter/environment:
`python -c "import beambending"`

If the last command doesn't return an error it means beambending is installed; then you are probably running your script with the wrong interpreter.
