### ISSUE TITLE
Teaching Environment for Educators using Python (Beginners)

### ISSUE THREAD

**Issue by desgarcia** [alfredocarella/simplebendingpractice#3]
@alfredocarella Using the BeamBending software using the launch binder in Git works well. I was wondering if you are able to create a "python tutorial steps" to complement the python coding environment for teachers and educators to use and carry out in their classes. I noticed installing the packages and using python to run the beambending software wasn't so clear compared to running it online in the launch binder. Many teachers might not have python expertise (including terminal executions), so including a detailed install instruction and example in the repository would be a great addition. 

@moorepants thoughts?

**Comment by moorepants** [comment]
@desgarcia This sounds fine. Improvements to the installation and getting started aspects of the documentation would be helpful. If you can provide some specifics of anything that was confusing I'm sure that would help @alfredocarella make the necessary changes.

**Comment by desgarcia** [comment]
@alfredocarella I'm not a python user, but I can manage my way around a coding system from my experience with different environments. During the install, I had some confusion on which Python version to download (depending on my computer OS/Linux/Windows). I think you should have a link to Python in the 'Installing the package' section (https://github.com/alfredocarella/simplebendingpractice). I was able to install using the:
pip install --user git+https://github.com/alfredocarella/simplebendingpractice but I think a novice user might need some guidance on python install and using the command window.

**Comment by nicoguaro** [comment]
@moorepants I think that this Issue discusses two things:

- Easiness of use: that might be tackled through a GUI or Jupyter notebooks + Widgets, for example.

- Easiness of installation.

I think that these two, are important but it is not clear to me what are the requirements for JOSE.

**Comment by moorepants** [comment]
The only requirement wrt to installation is:

Installation: Does installation proceed as outlined in the documentation? (and documentation is sufficient?)

But it is up to the reviewers to decide on tings beyond this. If the requests are not reasonable, then I'll work with the reviewers and the author to compromise. Sounds like @desgarcia is at least expressing that the documentation is not sufficient. Maybe pointing to some Python "getting started" external resources is sufficient (or not, its up to you). The ease of use aspect will have to be defined by you two.

**Comment by alfredocarella** [comment]
@desgarcia @nicoguaro A link has been added to a tutorial on how to install Python 3 on either Linux, Windows or MacOS.
Installation of the package can be skipped altogether by just using the provided Jupyter notebook hosted on mybinder
