### ISSUE TITLE
References for Engineering Statics Software or Programs

### ISSUE THREAD

**Issue by desgarcia** [alfredocarella/simplebendingpractice#4]
@alfredocarella Can you include more references for other types of similar software or programs related to engineering statics? I found this open learning tool for statics from Stanford University (https://oli.cmu.edu/courses/engineering-statics-open-free/). You can address these similar type programs and software, and how your tool is comparable and/or better, in the "Statement of Need" section of the paper.

**Comment by desgarcia** [comment]
@moorepants I saw your comment in the thread, and I agree and think @alfredocarella should include more software examples in the paper - and include how BeamBending is distinguished from the rest.

**Comment by alfredocarella** [comment]
@desgarcia I understand that the mentioned link (https://oli.cmu.edu/courses/engineering-statics-open-free/) is more of a theoretical module with quizzes at the end of each chapter to help students self-check their level of understanding.
However, there are as you mention quite a few software examples with similar capabilities. The "Statement of Need" section of the paper includes now a brief comparison with them (summarized in a table), including the main points that distinguish ```beambending``` from the rest.
