### ISSUE TITLE
PointTorque does not exist

### ISSUE THREAD

**Issue by nikorose87** [alfredocarella/simplebendingpractice#8]
Hi Alfredo,
First of all, I would like to thank you for such an amazing package. Now, I was using your library but the `PointTorque` cannot be loaded due to this class does not exist, either in the `beam` class or calling directly.

I do not know what can be happening.
Sincerely, 

Nikolay Prieto

**Comment by alfredocarella** [comment]
Hi Nikolay,
I'm glad to hear someone other than my students is using this. 
The `PointTorque` class exists in the master branch, but I see I have forgotten to create and upload a new release with it (sorry about that). I should be able to get it done soon (hopefully later today).

**Comment by alfredocarella** [comment]
Ok, now I have uploaded the new release (including PointTorque) to PyPI.
If you installed the package using pip, you only need to update your installation:
`pip install --upgrade beambending`
Thanks @nikorose87 for the heads up about this!
Regards,
Alfredo
