### ISSUE TITLE
syntax error in fig = beam.plot()

### ISSUE THREAD

**Issue by alfstella** [alfredocarella/simplebendingpractice#9]
Hi there, I have been trying to use this package and everything seems to work fine until I get to the fig = beam.plot() part, I always get a syntax error there.
This is my code, I have also tried having "pip install --user beambending" and "python3 -m pip install --user beambending" at the top but that just gives me another error. 
Do you know what the problem might be?

from beambending import beam

print('Specify the values of the variables')
#lengdirnar (Lengths)
l1 = int(input('L1: '))
l2 = int(input('L2: '))
a = int(input('a: '))
#samfellt álag (Distributed load, vertical)
q = int(input('q: '))
#stakur kraftur (Point load, vertical)
p = int(input('P: '))
#þversniðsstærðirnar (Cross section measurements)
b = int(input('b: '))
h = int(input('h: '))

beam = beam(l1+l2)
beam.pinned_support = l1
beam.rolling_support = (l1+l2)
beam.add_loads((
        PointLoadV(P, a),
        DistributedLoadV(q, (0, (l1+l2))
        ))

fig = beam.plot()

**Comment by alfredocarella** [comment]
> Hi there, I have been trying to use this package and everything seems to work fine until I get to the fig = beam.plot() part, I always get a syntax error there.
> This is my code, I have also tried having "pip install --user beambending" and "python3 -m pip install --user beambending" at the top but that just gives me another error.
> Do you know what the problem might be?
> 
> from beambending import beam
> 
> print('Specify the values of the variables')
> #lengdirnar (Lengths)
> l1 = int(input('L1: '))
> l2 = int(input('L2: '))
> a = int(input('a: '))
> #samfellt álag (Distributed load, vertical)
> q = int(input('q: '))
> #stakur kraftur (Point load, vertical)
> p = int(input('P: '))
> #þversniðsstærðirnar (Cross section measurements)
> b = int(input('b: '))
> h = int(input('h: '))
> 
> beam = beam(l1+l2)
> beam.pinned_support = l1
> beam.rolling_support = (l1+l2)
> beam.add_loads((
> PointLoadV(P, a),
> DistributedLoadV(q, (0, (l1+l2))
> ))
> 
> fig = beam.plot()

Hi @alfstella !
I see a couple of mistakes in your code... mainly forgetting that variables are case-sensitive and one missing parenthesis. The missing parenthesis was giving you the syntax error you mentioned. After you correct it, the other errors become evident.
Here comes a syntactically correct version of what I understand you intended to accomplish:

```

import matplotlib.pyplot as plt
from beambending import Beam, PointLoadV, DistributedLoadV

print('Specify the values of the variables')
#lengdirnar (Lengths)
l1 = int(input('L1: '))
l2 = int(input('L2: '))
a = int(input('a: '))
#samfellt álag (Distributed load, vertical)
q = int(input('q: '))
#stakur kraftur (Point load, vertical)
P = int(input('P: '))
#þversniðsstærðirnar (Cross section measurements)
b = int(input('b: '))
h = int(input('h: '))

beam = Beam(l1+l2)
beam.pinned_support = l1
beam.rolling_support = (l1+l2)
beam.add_loads((
PointLoadV(P, a),
DistributedLoadV(q, (0, (l1+l2)))
))

fig = beam.plot()
plt.savefig("my_beam_figure.png")
```

**Comment by alfstella** [comment]
Thank you so much for the help! This is exactly what I was trying to do :)
